#!/usr/bin/env bash
# ================================================================
# CLAUDE AGENTS LAUNCHER
# Works on Windows (Git Bash) and Linux/macOS
# Config lives in launch-agents-config.sh (same folder)
# ================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/launch-agents-config.sh"

if [[ ! -f "$CONFIG_FILE" ]]; then
    NAMES=() PATHS=() PROMPTS=()
    {
        echo "# CLAUDE AGENTS CONFIG"
        echo "# Generated by launcher. Edit via menu or directly."
        declare -p NAMES
        declare -p PATHS
        declare -p PROMPTS
    } > "$CONFIG_FILE"
fi

CYAN='\033[0;36m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

PATH_COLORS=(
    '\033[0;36m'   # cyan
    '\033[0;32m'   # green
    '\033[1;33m'   # yellow
    '\033[0;35m'   # magenta
    '\033[0;34m'   # blue
    '\033[0;31m'   # red
)

save_config() {
    local tmp="${CONFIG_FILE}.tmp.$$"
    {
        echo "# CLAUDE AGENTS CONFIG"
        echo "# Generated by launcher."
        declare -p NAMES
        declare -p PATHS
        declare -p PROMPTS
    } > "$tmp" && bash -n "$tmp" && mv -f "$tmp" "$CONFIG_FILE" || {
        rm -f "$tmp"
        echo -e "  ${RED}Error: failed to save config.${NC}"
    }
}

show_menu() {
    clear
    echo ""
    echo -e "  ${CYAN}============================================${NC}"
    echo -e "  ${CYAN} CLAUDE AGENTS LAUNCHER${NC}"
    echo -e "  ${CYAN}============================================${NC}"
    echo ""

    source "$CONFIG_FILE"
    COUNT=${#NAMES[@]}

    if [[ $COUNT -eq 0 ]]; then
        echo -e "  ${GRAY}No agents configured yet.${NC}"
    else
        echo -e "  ${YELLOW}Available agents:${NC}"
        echo ""
        for i in "${!NAMES[@]}"; do
            PC="${PATH_COLORS[$((i % ${#PATH_COLORS[@]}))]}"
            echo -e "  ${WHITE}[$((i+1))] ${NAMES[$i]}${NC}"
            echo -e "  ${PC}     ${PATHS[$i]}${NC}"
            echo ""
        done
    fi

    echo -e "  ${GREEN}[A]  Start ALL agents${NC}"
    echo -e "  ${CYAN}[+]  Add new agent${NC}"
    echo -e "  ${YELLOW}[E]  Edit an agent${NC}"
    echo -e "  ${RED}[-]  Remove an agent${NC}"
    echo -e "  ${GRAY}[Q]  Quit${NC}"
    echo ""
    echo -e "  ${YELLOW}Enter numbers (e.g. 1,3), A, +, E, - or Q:${NC}"
    echo ""
    read -r -p "  Your choice: " CHOICE
}

find_running_session() {
    local name="$1"
    local projects_dir
    projects_dir="$(cd ~ && pwd)/.claude/projects"
    [[ ! -d "$projects_dir" ]] && return 1

    # Find most recently modified JSONL containing this agent name (fixed-string, space-safe)
    local session_file="" newest_mtime=0 mtime f
    while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        mtime=$(stat -c %Y "$f" 2>/dev/null || stat -f %m "$f" 2>/dev/null || date -r "$f" +%s 2>/dev/null || echo 0)
        if [[ $mtime -gt $newest_mtime ]]; then
            newest_mtime=$mtime
            session_file="$f"
        fi
    done < <(grep -r --include="*.jsonl" -lF "\"agentName\": \"$name\"" "$projects_dir" 2>/dev/null)
    [[ -z "$session_file" ]] && return 1

    # If the tail contains turn_duration, the session has ended
    if tail -5 "$session_file" 2>/dev/null | grep -q '"turn_duration"'; then
        return 1
    fi

    basename "$session_file" .jsonl
}

launch_agent() {
    local name="$1"
    local path="$2"
    local prompt="$3"
    local silent="${4:-false}"  # true = bulk mode, skip without asking

    local existing
    existing=$(find_running_session "$name")

    if [[ -n "$existing" ]]; then
        if [[ "$silent" == "true" ]]; then
            echo -e "  ${YELLOW}-> ${name} already running, skipping${NC}"
            return
        fi
        echo ""
        echo -e "  ${YELLOW}-> ${name} is already running${NC}"
        echo -ne "  ${WHITE}[S]kip / [R]estart? ${NC}"
        read -r -n 1 ACTION
        echo ""
        ACTION=$(echo "$ACTION" | tr '[:lower:]' '[:upper:]')
        if [[ "$ACTION" != "R" ]]; then
            echo -e "  ${GRAY}   skipped${NC}"
            return
        fi
        claude stop "${existing:0:8}" &>/dev/null
        sleep 0.5
    fi

    if [[ ! -d "$path" ]]; then
        echo -e "  ${RED}Directory not found: ${path}${NC}"
        return 1
    fi

    echo -e "  ${WHITE}-> ${name}${NC}"
    echo -e "  ${GRAY}   ${path}${NC}"

    (cd -- "$path" && MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' \
        claude --dangerously-skip-permissions --bg --name "$name" "$prompt" \
        </dev/null >/dev/null 2>&1) &
    local pid=$!
    disown "$pid" 2>/dev/null
    sleep 1
}

add_agent() {
    source "$CONFIG_FILE"
    echo ""
    echo -e "  ${CYAN}--- Add New Agent ---${NC}"
    echo ""
    read -r -p "  Name (shown in agents view): " NEW_NAME
    read -r -p "  Path (project directory):    " NEW_PATH
    read -r -p "  Prompt (slash cmd or text):  " NEW_PROMPT

    if [[ -z "$NEW_NAME" || -z "$NEW_PATH" || -z "$NEW_PROMPT" ]]; then
        echo -e "  ${RED}Cancelled — all fields required.${NC}"
        sleep 1.5
        return
    fi

    NAMES+=("$NEW_NAME")
    PATHS+=("$NEW_PATH")
    PROMPTS+=("$NEW_PROMPT")
    save_config
    echo ""
    echo -e "  ${GREEN}Added: ${NEW_NAME}${NC}"
    sleep 1
}

edit_agent() {
    source "$CONFIG_FILE"
    COUNT=${#NAMES[@]}

    if [[ $COUNT -eq 0 ]]; then
        echo -e "  ${RED}Nothing to edit.${NC}"
        sleep 1.5
        return
    fi

    echo ""
    echo -e "  ${CYAN}--- Edit Agent ---${NC}"
    echo ""
    for i in "${!NAMES[@]}"; do
        PC="${PATH_COLORS[$((i % ${#PATH_COLORS[@]}))]}"
        echo -e "  ${WHITE}[$((i+1))] ${NAMES[$i]}${NC}"
        echo -e "  ${PC}     ${PATHS[$i]}${NC}"
        echo ""
    done
    read -r -p "  Number to edit (or Q to cancel): " SEL

    SEL_UP=$(echo "$SEL" | tr '[:lower:]' '[:upper:]' | tr -d ' ')
    if [[ "$SEL_UP" == "Q" ]]; then return; fi

    if [[ ! "$SEL" =~ ^[0-9]+$ ]]; then
        echo -e "  ${RED}Invalid number.${NC}"
        sleep 1.5
        return
    fi

    idx=$((10#$SEL - 1))
    if [[ $idx -lt 0 || $idx -ge $COUNT ]]; then
        echo -e "  ${RED}Invalid number.${NC}"
        sleep 1.5
        return
    fi

    echo ""
    echo -e "  ${GRAY}Leave blank to keep current value.${NC}"
    echo ""
    read -r -p "  Name    [${NAMES[$idx]}]: " NEW_NAME
    read -r -p "  Path    [${PATHS[$idx]}]: " NEW_PATH
    read -r -p "  Prompt  [${PROMPTS[$idx]}]: " NEW_PROMPT

    [[ -n "$NEW_NAME" ]]   && NAMES[$idx]="$NEW_NAME"
    [[ -n "$NEW_PATH" ]]   && PATHS[$idx]="$NEW_PATH"
    [[ -n "$NEW_PROMPT" ]] && PROMPTS[$idx]="$NEW_PROMPT"

    save_config
    echo ""
    echo -e "  ${GREEN}Updated: ${NAMES[$idx]}${NC}"
    sleep 1
}

remove_agent() {
    source "$CONFIG_FILE"
    COUNT=${#NAMES[@]}

    if [[ $COUNT -eq 0 ]]; then
        echo -e "  ${RED}Nothing to remove.${NC}"
        sleep 1.5
        return
    fi

    echo ""
    echo -e "  ${CYAN}--- Remove Agent ---${NC}"
    echo ""
    for i in "${!NAMES[@]}"; do
        PC="${PATH_COLORS[$((i % ${#PATH_COLORS[@]}))]}"
        echo -e "  ${WHITE}[$((i+1))] ${NAMES[$i]}${NC}"
        echo -e "  ${PC}     ${PATHS[$i]}${NC}"
        echo ""
    done
    read -r -p "  Number to remove (or Q to cancel): " SEL

    SEL_UP=$(echo "$SEL" | tr '[:lower:]' '[:upper:]' | tr -d ' ')
    if [[ "$SEL_UP" == "Q" ]]; then return; fi

    if [[ ! "$SEL" =~ ^[0-9]+$ ]]; then
        echo -e "  ${RED}Invalid number.${NC}"
        sleep 1.5
        return
    fi

    idx=$((10#$SEL - 1))
    if [[ $idx -lt 0 || $idx -ge $COUNT ]]; then
        echo -e "  ${RED}Invalid number.${NC}"
        sleep 1.5
        return
    fi

    REMOVED_NAME="${NAMES[$idx]}"
    NEW_NAMES=()
    NEW_PATHS=()
    NEW_PROMPTS=()
    for i in "${!NAMES[@]}"; do
        if [[ $i -ne $idx ]]; then
            NEW_NAMES+=("${NAMES[$i]}")
            NEW_PATHS+=("${PATHS[$i]}")
            NEW_PROMPTS+=("${PROMPTS[$i]}")
        fi
    done
    NAMES=("${NEW_NAMES[@]}")
    PATHS=("${NEW_PATHS[@]}")
    PROMPTS=("${NEW_PROMPTS[@]}")
    save_config
    echo ""
    echo -e "  ${RED}Removed: ${REMOVED_NAME}${NC}"
    sleep 1
}

# ---- Main loop ----

while true; do
    show_menu
    source "$CONFIG_FILE"
    COUNT=${#NAMES[@]}
    CHOICE_UP=$(echo "$CHOICE" | tr '[:lower:]' '[:upper:]' | tr -d ' ')

    case "$CHOICE_UP" in
        Q) echo ""; echo "  Bye."; echo ""; exit 0 ;;
        +) add_agent ;;
        E) edit_agent ;;
        -) remove_agent ;;
        A)
            echo ""
            for i in "${!NAMES[@]}"; do
                launch_agent "${NAMES[$i]}" "${PATHS[$i]}" "${PROMPTS[$i]}" "true"
            done
            echo ""
            echo -e "  ${GREEN}Done. Check agents view.${NC}"
            echo ""
            read -r -p "  Press Enter to close..."
            exit 0
            ;;
        *)
            LAUNCHED=0
            IFS=',' read -ra SELECTIONS <<< "$CHOICE"
            echo ""
            for sel in "${SELECTIONS[@]}"; do
                sel=$(echo "$sel" | tr -d ' ')
                if [[ ! "$sel" =~ ^[0-9]+$ ]]; then
                    echo -e "  ${YELLOW}Skipping invalid: ${sel}${NC}"
                    continue
                fi
                idx=$((10#$sel - 1))
                if [[ $idx -ge 0 && $idx -lt $COUNT ]]; then
                    launch_agent "${NAMES[$idx]}" "${PATHS[$idx]}" "${PROMPTS[$idx]}"
                    LAUNCHED=$((LAUNCHED + 1))
                else
                    echo -e "  ${YELLOW}Skipping invalid: ${sel}${NC}"
                fi
            done
            if [[ $LAUNCHED -gt 0 ]]; then
                echo ""
                echo -e "  ${GREEN}Done. Check agents view.${NC}"
                echo ""
                read -r -p "  Press Enter to close..."
                exit 0
            fi
            ;;
    esac
done
